services:
  backend:
    build: ./backend
    container_name: weather-backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: weather-frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
    restart: unless-stopped
